name: Checkout & Build & Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build_push:
    name: build image using Dockerfile
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag liorsol16/final-python:${{ github.run_number }}-${{ github.sha }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}

      - name: Push the image to registry
        run: docker push liorsol16/final-python:${{ github.run_number }}-${{ github.sha }}

